### ISSUE TITLE
TABLE에 row가 하나일 때 발생하는 문제

### ISSUE THREAD

**Issue by Seokxkyu** [DE32-3rd-team2/fastapi#2]
```
MariaDB [team2]> select * from face_age;
+-----+-------------+---------------------------------------------------------------+---------------------+-------------------+-----------------+--------+----------+
| num | origin_name | file_path                                                     | request_time        | prediction_result | prediction_time | answer | comments |
+-----+-------------+---------------------------------------------------------------+---------------------+-------------------+-----------------+--------+----------+
|   1 | ssk(1).jpeg | /home/ubuntu/images/11a57bb1-55b0-490f-afd9-a077b4c60057.jpeg | 2024-10-07 11:24:31 | NULL              | NULL            | NULL   | NULL     |
+-----+-------------+---------------------------------------------------------------+---------------------+-------------------+-----------------+--------+----------+
1 row in set (0.001 sec)
```

현재 face_age TABLE에 한개의 데이터 존재하고 있음에도, FastAPI 내의 http://43.201.16.62:8022/docs#/default/all_all_get 실행했을 때 아무런 값도 return 되지 않는 상황 발생

![image](https://github.com/user-attachments/assets/0852f6ce-c3be-4153-a447-85008b4ef122)

**Comment by Seokxkyu** [comment]
- 하나일 때 아무런 값을 리턴하지 않는 것이 아니라, 가장 최근에 추가된 이미지를 반환하지 못하는 상황
- ex. NUM=5까지 DB에 저장되어 있을 때 NUM=4의 사진까지 반환

**Comment by j25ng** [comment]
cursor.fetchmany(-1) => cursor.fetchall()로 변경 시 해결

데이터를 삽입한 후 cursor.rowcount를 호출하면, fetchmany로 값을 받아올 때 rowcount로 반환된 row는 포함하지 않고 결과값이 출력되기 때문에 faechall을 사용해서 값을 받아와야 함.

**Comment by j25ng** [comment]
cursor.fetchmany(-1) => cursor.fetchall()로 변경 시 해결

데이터를 삽입한 후 cursor.rowcount를 호출하면, fetchmany로 값을 받아올 때 rowcount로 반환된 row는 포함하지 않고 결과값이 출력되기 때문에 faechall을 사용해서 값을 받아와야 함.

**Comment by Seokxkyu** [comment]
정은님 방법으로 했더니 해결되었습니다. 감사합니다!
